apiVersion: v1
kind: Service
metadata:
  name: {{ include "tasks.componentName" (dict "root" $ "component" "backend") }}
  labels:
    {{- include "tasks.labels" (dict "root" $ "component" "backend") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
  selector:
    {{- include "tasks.selectorLabels" (dict "root" $ "component" "backend") | nindent 4 }}
